/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoanRouteImport } from './routes/student-loan'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SelfAssessmentRouteImport } from './routes/self-assessment'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PensionsRouteImport } from './routes/pensions'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as IsasRouteImport } from './routes/isas'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as IndexRouteImport } from './routes/index'

const StudentLoanRoute = StudentLoanRouteImport.update({
  id: '/student-loan',
  path: '/student-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfAssessmentRoute = SelfAssessmentRouteImport.update({
  id: '/self-assessment',
  path: '/self-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionsRoute = PensionsRouteImport.update({
  id: '/pensions',
  path: '/pensions',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const IsasRoute = IsasRouteImport.update({
  id: '/isas',
  path: '/isas',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/income': typeof IncomeRoute
  '/isas': typeof IsasRoute
  '/mortgage': typeof MortgageRoute
  '/pensions': typeof PensionsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/self-assessment': typeof SelfAssessmentRoute
  '/strategy': typeof StrategyRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/income': typeof IncomeRoute
  '/isas': typeof IsasRoute
  '/mortgage': typeof MortgageRoute
  '/pensions': typeof PensionsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/self-assessment': typeof SelfAssessmentRoute
  '/strategy': typeof StrategyRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/income': typeof IncomeRoute
  '/isas': typeof IsasRoute
  '/mortgage': typeof MortgageRoute
  '/pensions': typeof PensionsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/self-assessment': typeof SelfAssessmentRoute
  '/strategy': typeof StrategyRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eligibility'
    | '/income'
    | '/isas'
    | '/mortgage'
    | '/pensions'
    | '/portfolio'
    | '/profile'
    | '/savings'
    | '/self-assessment'
    | '/strategy'
    | '/student-loan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eligibility'
    | '/income'
    | '/isas'
    | '/mortgage'
    | '/pensions'
    | '/portfolio'
    | '/profile'
    | '/savings'
    | '/self-assessment'
    | '/strategy'
    | '/student-loan'
  id:
    | '__root__'
    | '/'
    | '/eligibility'
    | '/income'
    | '/isas'
    | '/mortgage'
    | '/pensions'
    | '/portfolio'
    | '/profile'
    | '/savings'
    | '/self-assessment'
    | '/strategy'
    | '/student-loan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EligibilityRoute: typeof EligibilityRoute
  IncomeRoute: typeof IncomeRoute
  IsasRoute: typeof IsasRoute
  MortgageRoute: typeof MortgageRoute
  PensionsRoute: typeof PensionsRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  SavingsRoute: typeof SavingsRoute
  SelfAssessmentRoute: typeof SelfAssessmentRoute
  StrategyRoute: typeof StrategyRoute
  StudentLoanRoute: typeof StudentLoanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-loan': {
      id: '/student-loan'
      path: '/student-loan'
      fullPath: '/student-loan'
      preLoaderRoute: typeof StudentLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-assessment': {
      id: '/self-assessment'
      path: '/self-assessment'
      fullPath: '/self-assessment'
      preLoaderRoute: typeof SelfAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pensions': {
      id: '/pensions'
      path: '/pensions'
      fullPath: '/pensions'
      preLoaderRoute: typeof PensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isas': {
      id: '/isas'
      path: '/isas'
      fullPath: '/isas'
      preLoaderRoute: typeof IsasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EligibilityRoute: EligibilityRoute,
  IncomeRoute: IncomeRoute,
  IsasRoute: IsasRoute,
  MortgageRoute: MortgageRoute,
  PensionsRoute: PensionsRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  SavingsRoute: SavingsRoute,
  SelfAssessmentRoute: SelfAssessmentRoute,
  StrategyRoute: StrategyRoute,
  StudentLoanRoute: StudentLoanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
