/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProcessesIndexRouteImport } from './routes/app.processes.index'
import { Route as AppAnalyzerIndexRouteImport } from './routes/app.analyzer.index'
import { Route as AppRunsIdRouteImport } from './routes/app.runs.$id'
import { Route as AppResearchNewRouteImport } from './routes/app.research.new'
import { Route as AppResearchJobIdRouteImport } from './routes/app.research.$jobId'
import { Route as AppProcessesIdRouteImport } from './routes/app.processes.$id'
import { Route as AppJobsJobIdRouteImport } from './routes/app.jobs.$jobId'
import { Route as AppAnalyzerIdRouteImport } from './routes/app.analyzer.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessesIndexRoute = AppProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzerIndexRoute = AppAnalyzerIndexRouteImport.update({
  id: '/analyzer/',
  path: '/analyzer/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchNewRoute = AppResearchNewRouteImport.update({
  id: '/research/new',
  path: '/research/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchJobIdRoute = AppResearchJobIdRouteImport.update({
  id: '/research/$jobId',
  path: '/research/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessesIdRoute = AppProcessesIdRouteImport.update({
  id: '/processes/$id',
  path: '/processes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzerIdRoute = AppAnalyzerIdRouteImport.update({
  id: '/analyzer/$id',
  path: '/analyzer/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/analyzer/$id': typeof AppAnalyzerIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/app/research/$jobId': typeof AppResearchJobIdRoute
  '/app/research/new': typeof AppResearchNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/analyzer/': typeof AppAnalyzerIndexRoute
  '/app/processes/': typeof AppProcessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppIndexRoute
  '/app/analyzer/$id': typeof AppAnalyzerIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/app/research/$jobId': typeof AppResearchJobIdRoute
  '/app/research/new': typeof AppResearchNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/analyzer': typeof AppAnalyzerIndexRoute
  '/app/processes': typeof AppProcessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/analyzer/$id': typeof AppAnalyzerIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/app/research/$jobId': typeof AppResearchJobIdRoute
  '/app/research/new': typeof AppResearchNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/analyzer/': typeof AppAnalyzerIndexRoute
  '/app/processes/': typeof AppProcessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/analyzer/$id'
    | '/app/jobs/$jobId'
    | '/app/processes/$id'
    | '/app/research/$jobId'
    | '/app/research/new'
    | '/app/runs/$id'
    | '/app/analyzer/'
    | '/app/processes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/analyzer/$id'
    | '/app/jobs/$jobId'
    | '/app/processes/$id'
    | '/app/research/$jobId'
    | '/app/research/new'
    | '/app/runs/$id'
    | '/app/analyzer'
    | '/app/processes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/analyzer/$id'
    | '/app/jobs/$jobId'
    | '/app/processes/$id'
    | '/app/research/$jobId'
    | '/app/research/new'
    | '/app/runs/$id'
    | '/app/analyzer/'
    | '/app/processes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processes/': {
      id: '/app/processes/'
      path: '/processes'
      fullPath: '/app/processes/'
      preLoaderRoute: typeof AppProcessesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyzer/': {
      id: '/app/analyzer/'
      path: '/analyzer'
      fullPath: '/app/analyzer/'
      preLoaderRoute: typeof AppAnalyzerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research/new': {
      id: '/app/research/new'
      path: '/research/new'
      fullPath: '/app/research/new'
      preLoaderRoute: typeof AppResearchNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research/$jobId': {
      id: '/app/research/$jobId'
      path: '/research/$jobId'
      fullPath: '/app/research/$jobId'
      preLoaderRoute: typeof AppResearchJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processes/$id': {
      id: '/app/processes/$id'
      path: '/processes/$id'
      fullPath: '/app/processes/$id'
      preLoaderRoute: typeof AppProcessesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/$jobId': {
      id: '/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyzer/$id': {
      id: '/app/analyzer/$id'
      path: '/analyzer/$id'
      fullPath: '/app/analyzer/$id'
      preLoaderRoute: typeof AppAnalyzerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyzerIdRoute: typeof AppAnalyzerIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppProcessesIdRoute: typeof AppProcessesIdRoute
  AppResearchJobIdRoute: typeof AppResearchJobIdRoute
  AppResearchNewRoute: typeof AppResearchNewRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppAnalyzerIndexRoute: typeof AppAnalyzerIndexRoute
  AppProcessesIndexRoute: typeof AppProcessesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAnalyzerIdRoute: AppAnalyzerIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppProcessesIdRoute: AppProcessesIdRoute,
  AppResearchJobIdRoute: AppResearchJobIdRoute,
  AppResearchNewRoute: AppResearchNewRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppAnalyzerIndexRoute: AppAnalyzerIndexRoute,
  AppProcessesIndexRoute: AppProcessesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
