import { Library, ExternalLink, Info } from "lucide-react";
import { getConcernEvidence } from "@/data/evidence-summary";
import { Card, Pill, Callout, buttonClasses } from "@/components/ui";
import { track } from "@/lib/analytics";

/* ────────────────────────────────────────────────────────────────────────────
   EVIDENCE SIGNAL  (compliance-safe aggregate)

   Renders the back-office AGGREGATE projection of the peer-reviewed corpus for a
   concern — counts only. It deliberately shows NO study titles, authors, venues,
   DOIs, remedy/supplement names, doses, per-tradition splits, or efficacy claims,
   and it states plainly that a research count is NOT a measure of whether any
   approach helps. The numbers describe the published literature on the TOPIC, not
   any of the traditions in the comparative lens — so no approach is implied to be
   evidence-backed or ranked above another.

   Source data: src/data/evidence-summary.ts (auto-generated by
   `npm run derive:evidence`, kept in the `npm run lint:content` scope as a
   standing guarantee). Education / context only — never advice, never a diagnosis.
   ──────────────────────────────────────────────────────────────────────────── */

type Bucket = { label: string; plural: string; n: number };

export function EvidenceSignal({ concernId }: { concernId: string }) {
  const ev = getConcernEvidence(concernId);
  if (!ev || ev.reviewCount === 0) return null;

  const { reviewCount, byType, mostRecentYear, sources, searchUrl } = ev;
  const n = (x: number) => x.toLocaleString("en-GB");

  const buckets: Bucket[] = [
    { label: "systematic review", plural: "systematic reviews", n: byType.systematicReview },
    { label: "meta-analysis", plural: "meta-analyses", n: byType.metaAnalysis },
    { label: "guideline", plural: "guidelines", n: byType.guideline },
    { label: "review", plural: "reviews", n: byType.review },
  ].filter((b) => b.n > 0);

  return (
    <Card className="p-6">
      <h2 className="flex items-center gap-2 font-serif text-xl">
        <Library className="h-5 w-5 text-primary" /> The wider evidence base
      </h2>
      <p className="mt-3 text-sm leading-relaxed text-foreground/90">
        This is an actively researched health topic. Independent, openly searchable
        databases index{" "}
        <strong className="font-semibold text-foreground">{n(reviewCount)}</strong>{" "}
        peer-reviewed evidence reviews related to it
        {mostRecentYear ? (
          <>
            , the most recent from{" "}
            <strong className="font-semibold text-foreground">{mostRecentYear}</strong>
          </>
        ) : null}
        .
      </p>

      {buckets.length > 0 && (
        <div className="mt-4 flex flex-wrap gap-1.5">
          {buckets.map((b) => (
            <Pill key={b.label} tint="primary">
              {n(b.n)} {b.n === 1 ? b.label : b.plural}
            </Pill>
          ))}
        </div>
      )}

      {sources.length > 0 && (
        <p className="mt-3 text-xs text-muted-foreground">Indexed via {sources.join(" · ")}.</p>
      )}

      <Callout tone="info" icon={<Info className="h-4 w-4" />} className="mt-4">
        A count of published research is not a measure of whether any approach helps.
        Reviews often reach mixed or inconclusive findings, and a study existing says
        nothing about what is right for you. This is general context about the topic —
        not advice about any specific approach, and not a judgement about you. A
        qualified, registered practitioner can help you make sense of it.
      </Callout>

      {searchUrl && (
        <div className="mt-4">
          <a
            href={searchUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => track("evidence_browse", { concernId, meta: { reviewCount } })}
            className={buttonClasses("outline", "sm")}
          >
            <ExternalLink className="h-4 w-4" /> Browse this research on Europe PMC
          </a>
        </div>
      )}
    </Card>
  );
}
