/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetitionsRouteImport } from './routes/petitions'
import { Route as ParliamentRouteImport } from './routes/parliament'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPetitionsRouteImport } from './routes/api/petitions'
import { Route as ApiKpisRouteImport } from './routes/api/kpis'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiContractsRouteImport } from './routes/api/contracts'
import { Route as ApiBriefingRouteImport } from './routes/api/briefing'
import { Route as ApiBillsRouteImport } from './routes/api/bills'

const PetitionsRoute = PetitionsRouteImport.update({
  id: '/petitions',
  path: '/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentRoute = ParliamentRouteImport.update({
  id: '/parliament',
  path: '/parliament',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetitionsRoute = ApiPetitionsRouteImport.update({
  id: '/api/petitions',
  path: '/api/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKpisRoute = ApiKpisRouteImport.update({
  id: '/api/kpis',
  path: '/api/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractsRoute = ApiContractsRouteImport.update({
  id: '/api/contracts',
  path: '/api/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefingRoute = ApiBriefingRouteImport.update({
  id: '/api/briefing',
  path: '/api/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsRoute = ApiBillsRouteImport.update({
  id: '/api/bills',
  path: '/api/bills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/parliament': typeof ParliamentRoute
  '/petitions': typeof PetitionsRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/petitions': typeof ApiPetitionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/parliament': typeof ParliamentRoute
  '/petitions': typeof PetitionsRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/petitions': typeof ApiPetitionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/parliament': typeof ParliamentRoute
  '/petitions': typeof PetitionsRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/petitions': typeof ApiPetitionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/contracts'
    | '/expenses'
    | '/parliament'
    | '/petitions'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/expenses'
    | '/api/kpis'
    | '/api/petitions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/contracts'
    | '/expenses'
    | '/parliament'
    | '/petitions'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/expenses'
    | '/api/kpis'
    | '/api/petitions'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/contracts'
    | '/expenses'
    | '/parliament'
    | '/petitions'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/expenses'
    | '/api/kpis'
    | '/api/petitions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  ContractsRoute: typeof ContractsRoute
  ExpensesRoute: typeof ExpensesRoute
  ParliamentRoute: typeof ParliamentRoute
  PetitionsRoute: typeof PetitionsRoute
  ApiBillsRoute: typeof ApiBillsRoute
  ApiBriefingRoute: typeof ApiBriefingRoute
  ApiContractsRoute: typeof ApiContractsRoute
  ApiExpensesRoute: typeof ApiExpensesRoute
  ApiKpisRoute: typeof ApiKpisRoute
  ApiPetitionsRoute: typeof ApiPetitionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/petitions': {
      id: '/petitions'
      path: '/petitions'
      fullPath: '/petitions'
      preLoaderRoute: typeof PetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament': {
      id: '/parliament'
      path: '/parliament'
      fullPath: '/parliament'
      preLoaderRoute: typeof ParliamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/petitions': {
      id: '/api/petitions'
      path: '/api/petitions'
      fullPath: '/api/petitions'
      preLoaderRoute: typeof ApiPetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kpis': {
      id: '/api/kpis'
      path: '/api/kpis'
      fullPath: '/api/kpis'
      preLoaderRoute: typeof ApiKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contracts': {
      id: '/api/contracts'
      path: '/api/contracts'
      fullPath: '/api/contracts'
      preLoaderRoute: typeof ApiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefing': {
      id: '/api/briefing'
      path: '/api/briefing'
      fullPath: '/api/briefing'
      preLoaderRoute: typeof ApiBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills': {
      id: '/api/bills'
      path: '/api/bills'
      fullPath: '/api/bills'
      preLoaderRoute: typeof ApiBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  ContractsRoute: ContractsRoute,
  ExpensesRoute: ExpensesRoute,
  ParliamentRoute: ParliamentRoute,
  PetitionsRoute: PetitionsRoute,
  ApiBillsRoute: ApiBillsRoute,
  ApiBriefingRoute: ApiBriefingRoute,
  ApiContractsRoute: ApiContractsRoute,
  ApiExpensesRoute: ApiExpensesRoute,
  ApiKpisRoute: ApiKpisRoute,
  ApiPetitionsRoute: ApiPetitionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
