/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotesRouteImport } from './routes/votes'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TakeActionRouteImport } from './routes/take-action'
import { Route as StopSearchRouteImport } from './routes/stop-search'
import { Route as SpendingRouteImport } from './routes/spending'
import { Route as SewageRouteImport } from './routes/sewage'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PetitionsRouteImport } from './routes/petitions'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ParliamentRouteImport } from './routes/parliament'
import { Route as NhsRouteImport } from './routes/nhs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyAreaRouteImport } from './routes/my-area'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LobbyingRouteImport } from './routes/lobbying'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FoiRouteImport } from './routes/foi'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as CrossrefRouteImport } from './routes/crossref'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as BathingWaterRouteImport } from './routes/bathing-water'
import { Route as AcobaRouteImport } from './routes/acoba'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as IssuesIssueRouteImport } from './routes/issues/$issue'
import { Route as ApiVotesRouteImport } from './routes/api/votes'
import { Route as ApiStopSearchRouteImport } from './routes/api/stop-search'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSpendingRouteImport } from './routes/api/spending'
import { Route as ApiSewageRouteImport } from './routes/api/sewage'
import { Route as ApiSanctionsRouteImport } from './routes/api/sanctions'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPostcodeRouteImport } from './routes/api/postcode'
import { Route as ApiPetitionsRouteImport } from './routes/api/petitions'
import { Route as ApiPartiesRouteImport } from './routes/api/parties'
import { Route as ApiNhsRouteImport } from './routes/api/nhs'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiMpRouteImport } from './routes/api/mp'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiLobbyingRouteImport } from './routes/api/lobbying'
import { Route as ApiKpisRouteImport } from './routes/api/kpis'
import { Route as ApiFoiRouteImport } from './routes/api/foi'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiEconomyRouteImport } from './routes/api/economy'
import { Route as ApiDonationsRouteImport } from './routes/api/donations'
import { Route as ApiContractsRouteImport } from './routes/api/contracts'
import { Route as ApiConstituencyMpRouteImport } from './routes/api/constituency-mp'
import { Route as ApiCommitteesRouteImport } from './routes/api/committees'
import { Route as ApiBillsRouteImport } from './routes/api/bills'
import { Route as ApiBathingWaterRouteImport } from './routes/api/bathing-water'
import { Route as ApiAcobaRouteImport } from './routes/api/acoba'
import { Route as PartiesPledgeIdRouteImport } from './routes/parties.pledge.$id'

const VotesRoute = VotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeActionRoute = TakeActionRouteImport.update({
  id: '/take-action',
  path: '/take-action',
  getParentRoute: () => rootRouteImport,
} as any)
const StopSearchRoute = StopSearchRouteImport.update({
  id: '/stop-search',
  path: '/stop-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingRoute = SpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const SewageRoute = SewageRouteImport.update({
  id: '/sewage',
  path: '/sewage',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsRoute = PetitionsRouteImport.update({
  id: '/petitions',
  path: '/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentRoute = ParliamentRouteImport.update({
  id: '/parliament',
  path: '/parliament',
  getParentRoute: () => rootRouteImport,
} as any)
const NhsRoute = NhsRouteImport.update({
  id: '/nhs',
  path: '/nhs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAreaRoute = MyAreaRouteImport.update({
  id: '/my-area',
  path: '/my-area',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyingRoute = LobbyingRouteImport.update({
  id: '/lobbying',
  path: '/lobbying',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FoiRoute = FoiRouteImport.update({
  id: '/foi',
  path: '/foi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossrefRoute = CrossrefRouteImport.update({
  id: '/crossref',
  path: '/crossref',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const BathingWaterRoute = BathingWaterRouteImport.update({
  id: '/bathing-water',
  path: '/bathing-water',
  getParentRoute: () => rootRouteImport,
} as any)
const AcobaRoute = AcobaRouteImport.update({
  id: '/acoba',
  path: '/acoba',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const IssuesIssueRoute = IssuesIssueRouteImport.update({
  id: '/issues/$issue',
  path: '/issues/$issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesRoute = ApiVotesRouteImport.update({
  id: '/api/votes',
  path: '/api/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopSearchRoute = ApiStopSearchRouteImport.update({
  id: '/api/stop-search',
  path: '/api/stop-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpendingRoute = ApiSpendingRouteImport.update({
  id: '/api/spending',
  path: '/api/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSewageRoute = ApiSewageRouteImport.update({
  id: '/api/sewage',
  path: '/api/sewage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSanctionsRoute = ApiSanctionsRouteImport.update({
  id: '/api/sanctions',
  path: '/api/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostcodeRoute = ApiPostcodeRouteImport.update({
  id: '/api/postcode',
  path: '/api/postcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetitionsRoute = ApiPetitionsRouteImport.update({
  id: '/api/petitions',
  path: '/api/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartiesRoute = ApiPartiesRouteImport.update({
  id: '/api/parties',
  path: '/api/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNhsRoute = ApiNhsRouteImport.update({
  id: '/api/nhs',
  path: '/api/nhs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpRoute = ApiMpRouteImport.update({
  id: '/api/mp',
  path: '/api/mp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLobbyingRoute = ApiLobbyingRouteImport.update({
  id: '/api/lobbying',
  path: '/api/lobbying',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKpisRoute = ApiKpisRouteImport.update({
  id: '/api/kpis',
  path: '/api/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoiRoute = ApiFoiRouteImport.update({
  id: '/api/foi',
  path: '/api/foi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomyRoute = ApiEconomyRouteImport.update({
  id: '/api/economy',
  path: '/api/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsRoute = ApiDonationsRouteImport.update({
  id: '/api/donations',
  path: '/api/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractsRoute = ApiContractsRouteImport.update({
  id: '/api/contracts',
  path: '/api/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConstituencyMpRoute = ApiConstituencyMpRouteImport.update({
  id: '/api/constituency-mp',
  path: '/api/constituency-mp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitteesRoute = ApiCommitteesRouteImport.update({
  id: '/api/committees',
  path: '/api/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsRoute = ApiBillsRouteImport.update({
  id: '/api/bills',
  path: '/api/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBathingWaterRoute = ApiBathingWaterRouteImport.update({
  id: '/api/bathing-water',
  path: '/api/bathing-water',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcobaRoute = ApiAcobaRouteImport.update({
  id: '/api/acoba',
  path: '/api/acoba',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesPledgeIdRoute = PartiesPledgeIdRouteImport.update({
  id: '/pledge/$id',
  path: '/pledge/$id',
  getParentRoute: () => PartiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acoba': typeof AcobaRoute
  '/bathing-water': typeof BathingWaterRoute
  '/citations': typeof CitationsRoute
  '/committees': typeof CommitteesRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/economy': typeof EconomyRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/learn': typeof LearnRouteWithChildren
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/methodology': typeof MethodologyRoute
  '/my-area': typeof MyAreaRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRouteWithChildren
  '/petitions': typeof PetitionsRoute
  '/projects': typeof ProjectsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/spending': typeof SpendingRoute
  '/stop-search': typeof StopSearchRoute
  '/take-action': typeof TakeActionRoute
  '/tools': typeof ToolsRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bathing-water': typeof ApiBathingWaterRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/committees': typeof ApiCommitteesRoute
  '/api/constituency-mp': typeof ApiConstituencyMpRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/economy': typeof ApiEconomyRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/mp': typeof ApiMpRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/postcode': typeof ApiPostcodeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/spending': typeof ApiSpendingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
  '/issues/$issue': typeof IssuesIssueRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/issues/': typeof IssuesIndexRoute
  '/parties/pledge/$id': typeof PartiesPledgeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acoba': typeof AcobaRoute
  '/bathing-water': typeof BathingWaterRoute
  '/citations': typeof CitationsRoute
  '/committees': typeof CommitteesRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/economy': typeof EconomyRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/learn': typeof LearnRouteWithChildren
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/methodology': typeof MethodologyRoute
  '/my-area': typeof MyAreaRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRouteWithChildren
  '/petitions': typeof PetitionsRoute
  '/projects': typeof ProjectsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/spending': typeof SpendingRoute
  '/stop-search': typeof StopSearchRoute
  '/take-action': typeof TakeActionRoute
  '/tools': typeof ToolsRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bathing-water': typeof ApiBathingWaterRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/committees': typeof ApiCommitteesRoute
  '/api/constituency-mp': typeof ApiConstituencyMpRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/economy': typeof ApiEconomyRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/mp': typeof ApiMpRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/postcode': typeof ApiPostcodeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/spending': typeof ApiSpendingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
  '/issues/$issue': typeof IssuesIssueRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/issues': typeof IssuesIndexRoute
  '/parties/pledge/$id': typeof PartiesPledgeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acoba': typeof AcobaRoute
  '/bathing-water': typeof BathingWaterRoute
  '/citations': typeof CitationsRoute
  '/committees': typeof CommitteesRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/economy': typeof EconomyRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/learn': typeof LearnRouteWithChildren
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/methodology': typeof MethodologyRoute
  '/my-area': typeof MyAreaRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRouteWithChildren
  '/petitions': typeof PetitionsRoute
  '/projects': typeof ProjectsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/spending': typeof SpendingRoute
  '/stop-search': typeof StopSearchRoute
  '/take-action': typeof TakeActionRoute
  '/tools': typeof ToolsRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bathing-water': typeof ApiBathingWaterRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/committees': typeof ApiCommitteesRoute
  '/api/constituency-mp': typeof ApiConstituencyMpRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/economy': typeof ApiEconomyRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/mp': typeof ApiMpRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/postcode': typeof ApiPostcodeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/spending': typeof ApiSpendingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
  '/issues/$issue': typeof IssuesIssueRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/issues/': typeof IssuesIndexRoute
  '/parties/pledge/$id': typeof PartiesPledgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acoba'
    | '/bathing-water'
    | '/citations'
    | '/committees'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/economy'
    | '/expenses'
    | '/foi'
    | '/learn'
    | '/lobbying'
    | '/meetings'
    | '/methodology'
    | '/my-area'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/projects'
    | '/sanctions'
    | '/sewage'
    | '/spending'
    | '/stop-search'
    | '/take-action'
    | '/tools'
    | '/votes'
    | '/api/acoba'
    | '/api/bathing-water'
    | '/api/bills'
    | '/api/committees'
    | '/api/constituency-mp'
    | '/api/contracts'
    | '/api/donations'
    | '/api/economy'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/mp'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/postcode'
    | '/api/projects'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/spending'
    | '/api/status'
    | '/api/stop-search'
    | '/api/votes'
    | '/issues/$issue'
    | '/learn/$slug'
    | '/issues/'
    | '/parties/pledge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acoba'
    | '/bathing-water'
    | '/citations'
    | '/committees'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/economy'
    | '/expenses'
    | '/foi'
    | '/learn'
    | '/lobbying'
    | '/meetings'
    | '/methodology'
    | '/my-area'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/projects'
    | '/sanctions'
    | '/sewage'
    | '/spending'
    | '/stop-search'
    | '/take-action'
    | '/tools'
    | '/votes'
    | '/api/acoba'
    | '/api/bathing-water'
    | '/api/bills'
    | '/api/committees'
    | '/api/constituency-mp'
    | '/api/contracts'
    | '/api/donations'
    | '/api/economy'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/mp'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/postcode'
    | '/api/projects'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/spending'
    | '/api/status'
    | '/api/stop-search'
    | '/api/votes'
    | '/issues/$issue'
    | '/learn/$slug'
    | '/issues'
    | '/parties/pledge/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acoba'
    | '/bathing-water'
    | '/citations'
    | '/committees'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/economy'
    | '/expenses'
    | '/foi'
    | '/learn'
    | '/lobbying'
    | '/meetings'
    | '/methodology'
    | '/my-area'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/projects'
    | '/sanctions'
    | '/sewage'
    | '/spending'
    | '/stop-search'
    | '/take-action'
    | '/tools'
    | '/votes'
    | '/api/acoba'
    | '/api/bathing-water'
    | '/api/bills'
    | '/api/committees'
    | '/api/constituency-mp'
    | '/api/contracts'
    | '/api/donations'
    | '/api/economy'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/mp'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/postcode'
    | '/api/projects'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/spending'
    | '/api/status'
    | '/api/stop-search'
    | '/api/votes'
    | '/issues/$issue'
    | '/learn/$slug'
    | '/issues/'
    | '/parties/pledge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcobaRoute: typeof AcobaRoute
  BathingWaterRoute: typeof BathingWaterRoute
  CitationsRoute: typeof CitationsRoute
  CommitteesRoute: typeof CommitteesRoute
  ContractsRoute: typeof ContractsRoute
  CrossrefRoute: typeof CrossrefRoute
  DonationsRoute: typeof DonationsRoute
  EconomyRoute: typeof EconomyRoute
  ExpensesRoute: typeof ExpensesRoute
  FoiRoute: typeof FoiRoute
  LearnRoute: typeof LearnRouteWithChildren
  LobbyingRoute: typeof LobbyingRoute
  MeetingsRoute: typeof MeetingsRoute
  MethodologyRoute: typeof MethodologyRoute
  MyAreaRoute: typeof MyAreaRoute
  NewsRoute: typeof NewsRoute
  NhsRoute: typeof NhsRoute
  ParliamentRoute: typeof ParliamentRoute
  PartiesRoute: typeof PartiesRouteWithChildren
  PetitionsRoute: typeof PetitionsRoute
  ProjectsRoute: typeof ProjectsRoute
  SanctionsRoute: typeof SanctionsRoute
  SewageRoute: typeof SewageRoute
  SpendingRoute: typeof SpendingRoute
  StopSearchRoute: typeof StopSearchRoute
  TakeActionRoute: typeof TakeActionRoute
  ToolsRoute: typeof ToolsRoute
  VotesRoute: typeof VotesRoute
  ApiAcobaRoute: typeof ApiAcobaRoute
  ApiBathingWaterRoute: typeof ApiBathingWaterRoute
  ApiBillsRoute: typeof ApiBillsRoute
  ApiCommitteesRoute: typeof ApiCommitteesRoute
  ApiConstituencyMpRoute: typeof ApiConstituencyMpRoute
  ApiContractsRoute: typeof ApiContractsRoute
  ApiDonationsRoute: typeof ApiDonationsRoute
  ApiEconomyRoute: typeof ApiEconomyRoute
  ApiExpensesRoute: typeof ApiExpensesRoute
  ApiFoiRoute: typeof ApiFoiRoute
  ApiKpisRoute: typeof ApiKpisRoute
  ApiLobbyingRoute: typeof ApiLobbyingRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiMpRoute: typeof ApiMpRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiNhsRoute: typeof ApiNhsRoute
  ApiPartiesRoute: typeof ApiPartiesRoute
  ApiPetitionsRoute: typeof ApiPetitionsRoute
  ApiPostcodeRoute: typeof ApiPostcodeRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiSanctionsRoute: typeof ApiSanctionsRoute
  ApiSewageRoute: typeof ApiSewageRoute
  ApiSpendingRoute: typeof ApiSpendingRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiStopSearchRoute: typeof ApiStopSearchRoute
  ApiVotesRoute: typeof ApiVotesRoute
  IssuesIssueRoute: typeof IssuesIssueRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/votes': {
      id: '/votes'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take-action': {
      id: '/take-action'
      path: '/take-action'
      fullPath: '/take-action'
      preLoaderRoute: typeof TakeActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-search': {
      id: '/stop-search'
      path: '/stop-search'
      fullPath: '/stop-search'
      preLoaderRoute: typeof StopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending': {
      id: '/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof SpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewage': {
      id: '/sewage'
      path: '/sewage'
      fullPath: '/sewage'
      preLoaderRoute: typeof SewageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions': {
      id: '/petitions'
      path: '/petitions'
      fullPath: '/petitions'
      preLoaderRoute: typeof PetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament': {
      id: '/parliament'
      path: '/parliament'
      fullPath: '/parliament'
      preLoaderRoute: typeof ParliamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhs': {
      id: '/nhs'
      path: '/nhs'
      fullPath: '/nhs'
      preLoaderRoute: typeof NhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-area': {
      id: '/my-area'
      path: '/my-area'
      fullPath: '/my-area'
      preLoaderRoute: typeof MyAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbying': {
      id: '/lobbying'
      path: '/lobbying'
      fullPath: '/lobbying'
      preLoaderRoute: typeof LobbyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foi': {
      id: '/foi'
      path: '/foi'
      fullPath: '/foi'
      preLoaderRoute: typeof FoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossref': {
      id: '/crossref'
      path: '/crossref'
      fullPath: '/crossref'
      preLoaderRoute: typeof CrossrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathing-water': {
      id: '/bathing-water'
      path: '/bathing-water'
      fullPath: '/bathing-water'
      preLoaderRoute: typeof BathingWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoba': {
      id: '/acoba'
      path: '/acoba'
      fullPath: '/acoba'
      preLoaderRoute: typeof AcobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/issues/$issue': {
      id: '/issues/$issue'
      path: '/issues/$issue'
      fullPath: '/issues/$issue'
      preLoaderRoute: typeof IssuesIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes': {
      id: '/api/votes'
      path: '/api/votes'
      fullPath: '/api/votes'
      preLoaderRoute: typeof ApiVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stop-search': {
      id: '/api/stop-search'
      path: '/api/stop-search'
      fullPath: '/api/stop-search'
      preLoaderRoute: typeof ApiStopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spending': {
      id: '/api/spending'
      path: '/api/spending'
      fullPath: '/api/spending'
      preLoaderRoute: typeof ApiSpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sewage': {
      id: '/api/sewage'
      path: '/api/sewage'
      fullPath: '/api/sewage'
      preLoaderRoute: typeof ApiSewageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sanctions': {
      id: '/api/sanctions'
      path: '/api/sanctions'
      fullPath: '/api/sanctions'
      preLoaderRoute: typeof ApiSanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postcode': {
      id: '/api/postcode'
      path: '/api/postcode'
      fullPath: '/api/postcode'
      preLoaderRoute: typeof ApiPostcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/petitions': {
      id: '/api/petitions'
      path: '/api/petitions'
      fullPath: '/api/petitions'
      preLoaderRoute: typeof ApiPetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parties': {
      id: '/api/parties'
      path: '/api/parties'
      fullPath: '/api/parties'
      preLoaderRoute: typeof ApiPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nhs': {
      id: '/api/nhs'
      path: '/api/nhs'
      fullPath: '/api/nhs'
      preLoaderRoute: typeof ApiNhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp': {
      id: '/api/mp'
      path: '/api/mp'
      fullPath: '/api/mp'
      preLoaderRoute: typeof ApiMpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lobbying': {
      id: '/api/lobbying'
      path: '/api/lobbying'
      fullPath: '/api/lobbying'
      preLoaderRoute: typeof ApiLobbyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kpis': {
      id: '/api/kpis'
      path: '/api/kpis'
      fullPath: '/api/kpis'
      preLoaderRoute: typeof ApiKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foi': {
      id: '/api/foi'
      path: '/api/foi'
      fullPath: '/api/foi'
      preLoaderRoute: typeof ApiFoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economy': {
      id: '/api/economy'
      path: '/api/economy'
      fullPath: '/api/economy'
      preLoaderRoute: typeof ApiEconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations': {
      id: '/api/donations'
      path: '/api/donations'
      fullPath: '/api/donations'
      preLoaderRoute: typeof ApiDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contracts': {
      id: '/api/contracts'
      path: '/api/contracts'
      fullPath: '/api/contracts'
      preLoaderRoute: typeof ApiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/constituency-mp': {
      id: '/api/constituency-mp'
      path: '/api/constituency-mp'
      fullPath: '/api/constituency-mp'
      preLoaderRoute: typeof ApiConstituencyMpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/committees': {
      id: '/api/committees'
      path: '/api/committees'
      fullPath: '/api/committees'
      preLoaderRoute: typeof ApiCommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills': {
      id: '/api/bills'
      path: '/api/bills'
      fullPath: '/api/bills'
      preLoaderRoute: typeof ApiBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bathing-water': {
      id: '/api/bathing-water'
      path: '/api/bathing-water'
      fullPath: '/api/bathing-water'
      preLoaderRoute: typeof ApiBathingWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/acoba': {
      id: '/api/acoba'
      path: '/api/acoba'
      fullPath: '/api/acoba'
      preLoaderRoute: typeof ApiAcobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/pledge/$id': {
      id: '/parties/pledge/$id'
      path: '/pledge/$id'
      fullPath: '/parties/pledge/$id'
      preLoaderRoute: typeof PartiesPledgeIdRouteImport
      parentRoute: typeof PartiesRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface PartiesRouteChildren {
  PartiesPledgeIdRoute: typeof PartiesPledgeIdRoute
}

const PartiesRouteChildren: PartiesRouteChildren = {
  PartiesPledgeIdRoute: PartiesPledgeIdRoute,
}

const PartiesRouteWithChildren =
  PartiesRoute._addFileChildren(PartiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcobaRoute: AcobaRoute,
  BathingWaterRoute: BathingWaterRoute,
  CitationsRoute: CitationsRoute,
  CommitteesRoute: CommitteesRoute,
  ContractsRoute: ContractsRoute,
  CrossrefRoute: CrossrefRoute,
  DonationsRoute: DonationsRoute,
  EconomyRoute: EconomyRoute,
  ExpensesRoute: ExpensesRoute,
  FoiRoute: FoiRoute,
  LearnRoute: LearnRouteWithChildren,
  LobbyingRoute: LobbyingRoute,
  MeetingsRoute: MeetingsRoute,
  MethodologyRoute: MethodologyRoute,
  MyAreaRoute: MyAreaRoute,
  NewsRoute: NewsRoute,
  NhsRoute: NhsRoute,
  ParliamentRoute: ParliamentRoute,
  PartiesRoute: PartiesRouteWithChildren,
  PetitionsRoute: PetitionsRoute,
  ProjectsRoute: ProjectsRoute,
  SanctionsRoute: SanctionsRoute,
  SewageRoute: SewageRoute,
  SpendingRoute: SpendingRoute,
  StopSearchRoute: StopSearchRoute,
  TakeActionRoute: TakeActionRoute,
  ToolsRoute: ToolsRoute,
  VotesRoute: VotesRoute,
  ApiAcobaRoute: ApiAcobaRoute,
  ApiBathingWaterRoute: ApiBathingWaterRoute,
  ApiBillsRoute: ApiBillsRoute,
  ApiCommitteesRoute: ApiCommitteesRoute,
  ApiConstituencyMpRoute: ApiConstituencyMpRoute,
  ApiContractsRoute: ApiContractsRoute,
  ApiDonationsRoute: ApiDonationsRoute,
  ApiEconomyRoute: ApiEconomyRoute,
  ApiExpensesRoute: ApiExpensesRoute,
  ApiFoiRoute: ApiFoiRoute,
  ApiKpisRoute: ApiKpisRoute,
  ApiLobbyingRoute: ApiLobbyingRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiMpRoute: ApiMpRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiNhsRoute: ApiNhsRoute,
  ApiPartiesRoute: ApiPartiesRoute,
  ApiPetitionsRoute: ApiPetitionsRoute,
  ApiPostcodeRoute: ApiPostcodeRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiSanctionsRoute: ApiSanctionsRoute,
  ApiSewageRoute: ApiSewageRoute,
  ApiSpendingRoute: ApiSpendingRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiStopSearchRoute: ApiStopSearchRoute,
  ApiVotesRoute: ApiVotesRoute,
  IssuesIssueRoute: IssuesIssueRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
