/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotesRouteImport } from './routes/votes'
import { Route as StopSearchRouteImport } from './routes/stop-search'
import { Route as SewageRouteImport } from './routes/sewage'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as PetitionsRouteImport } from './routes/petitions'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ParliamentRouteImport } from './routes/parliament'
import { Route as NhsRouteImport } from './routes/nhs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LobbyingRouteImport } from './routes/lobbying'
import { Route as FoiRouteImport } from './routes/foi'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as CrossrefRouteImport } from './routes/crossref'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as AcobaRouteImport } from './routes/acoba'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVotesRouteImport } from './routes/api/votes'
import { Route as ApiStopSearchRouteImport } from './routes/api/stop-search'
import { Route as ApiSewageRouteImport } from './routes/api/sewage'
import { Route as ApiSanctionsRouteImport } from './routes/api/sanctions'
import { Route as ApiPetitionsRouteImport } from './routes/api/petitions'
import { Route as ApiPartiesRouteImport } from './routes/api/parties'
import { Route as ApiNhsRouteImport } from './routes/api/nhs'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiLobbyingRouteImport } from './routes/api/lobbying'
import { Route as ApiKpisRouteImport } from './routes/api/kpis'
import { Route as ApiFoiRouteImport } from './routes/api/foi'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiDonationsRouteImport } from './routes/api/donations'
import { Route as ApiContractsRouteImport } from './routes/api/contracts'
import { Route as ApiBriefingRouteImport } from './routes/api/briefing'
import { Route as ApiBillsRouteImport } from './routes/api/bills'
import { Route as ApiAcobaRouteImport } from './routes/api/acoba'

const VotesRoute = VotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const StopSearchRoute = StopSearchRouteImport.update({
  id: '/stop-search',
  path: '/stop-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SewageRoute = SewageRouteImport.update({
  id: '/sewage',
  path: '/sewage',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsRoute = PetitionsRouteImport.update({
  id: '/petitions',
  path: '/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentRoute = ParliamentRouteImport.update({
  id: '/parliament',
  path: '/parliament',
  getParentRoute: () => rootRouteImport,
} as any)
const NhsRoute = NhsRouteImport.update({
  id: '/nhs',
  path: '/nhs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyingRoute = LobbyingRouteImport.update({
  id: '/lobbying',
  path: '/lobbying',
  getParentRoute: () => rootRouteImport,
} as any)
const FoiRoute = FoiRouteImport.update({
  id: '/foi',
  path: '/foi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossrefRoute = CrossrefRouteImport.update({
  id: '/crossref',
  path: '/crossref',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const AcobaRoute = AcobaRouteImport.update({
  id: '/acoba',
  path: '/acoba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesRoute = ApiVotesRouteImport.update({
  id: '/api/votes',
  path: '/api/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopSearchRoute = ApiStopSearchRouteImport.update({
  id: '/api/stop-search',
  path: '/api/stop-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSewageRoute = ApiSewageRouteImport.update({
  id: '/api/sewage',
  path: '/api/sewage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSanctionsRoute = ApiSanctionsRouteImport.update({
  id: '/api/sanctions',
  path: '/api/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetitionsRoute = ApiPetitionsRouteImport.update({
  id: '/api/petitions',
  path: '/api/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartiesRoute = ApiPartiesRouteImport.update({
  id: '/api/parties',
  path: '/api/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNhsRoute = ApiNhsRouteImport.update({
  id: '/api/nhs',
  path: '/api/nhs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLobbyingRoute = ApiLobbyingRouteImport.update({
  id: '/api/lobbying',
  path: '/api/lobbying',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKpisRoute = ApiKpisRouteImport.update({
  id: '/api/kpis',
  path: '/api/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoiRoute = ApiFoiRouteImport.update({
  id: '/api/foi',
  path: '/api/foi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsRoute = ApiDonationsRouteImport.update({
  id: '/api/donations',
  path: '/api/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractsRoute = ApiContractsRouteImport.update({
  id: '/api/contracts',
  path: '/api/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefingRoute = ApiBriefingRouteImport.update({
  id: '/api/briefing',
  path: '/api/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsRoute = ApiBillsRouteImport.update({
  id: '/api/bills',
  path: '/api/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcobaRoute = ApiAcobaRouteImport.update({
  id: '/api/acoba',
  path: '/api/acoba',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoba': typeof AcobaRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRoute
  '/petitions': typeof PetitionsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/stop-search': typeof StopSearchRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoba': typeof AcobaRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRoute
  '/petitions': typeof PetitionsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/stop-search': typeof StopSearchRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoba': typeof AcobaRoute
  '/briefing': typeof BriefingRoute
  '/contracts': typeof ContractsRoute
  '/crossref': typeof CrossrefRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/foi': typeof FoiRoute
  '/lobbying': typeof LobbyingRoute
  '/meetings': typeof MeetingsRoute
  '/news': typeof NewsRoute
  '/nhs': typeof NhsRoute
  '/parliament': typeof ParliamentRoute
  '/parties': typeof PartiesRoute
  '/petitions': typeof PetitionsRoute
  '/sanctions': typeof SanctionsRoute
  '/sewage': typeof SewageRoute
  '/stop-search': typeof StopSearchRoute
  '/votes': typeof VotesRoute
  '/api/acoba': typeof ApiAcobaRoute
  '/api/bills': typeof ApiBillsRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/contracts': typeof ApiContractsRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/foi': typeof ApiFoiRoute
  '/api/kpis': typeof ApiKpisRoute
  '/api/lobbying': typeof ApiLobbyingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/nhs': typeof ApiNhsRoute
  '/api/parties': typeof ApiPartiesRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/sanctions': typeof ApiSanctionsRoute
  '/api/sewage': typeof ApiSewageRoute
  '/api/stop-search': typeof ApiStopSearchRoute
  '/api/votes': typeof ApiVotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoba'
    | '/briefing'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/expenses'
    | '/foi'
    | '/lobbying'
    | '/meetings'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/sanctions'
    | '/sewage'
    | '/stop-search'
    | '/votes'
    | '/api/acoba'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/donations'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/stop-search'
    | '/api/votes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoba'
    | '/briefing'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/expenses'
    | '/foi'
    | '/lobbying'
    | '/meetings'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/sanctions'
    | '/sewage'
    | '/stop-search'
    | '/votes'
    | '/api/acoba'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/donations'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/stop-search'
    | '/api/votes'
  id:
    | '__root__'
    | '/'
    | '/acoba'
    | '/briefing'
    | '/contracts'
    | '/crossref'
    | '/donations'
    | '/expenses'
    | '/foi'
    | '/lobbying'
    | '/meetings'
    | '/news'
    | '/nhs'
    | '/parliament'
    | '/parties'
    | '/petitions'
    | '/sanctions'
    | '/sewage'
    | '/stop-search'
    | '/votes'
    | '/api/acoba'
    | '/api/bills'
    | '/api/briefing'
    | '/api/contracts'
    | '/api/donations'
    | '/api/expenses'
    | '/api/foi'
    | '/api/kpis'
    | '/api/lobbying'
    | '/api/meetings'
    | '/api/news'
    | '/api/nhs'
    | '/api/parties'
    | '/api/petitions'
    | '/api/sanctions'
    | '/api/sewage'
    | '/api/stop-search'
    | '/api/votes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcobaRoute: typeof AcobaRoute
  BriefingRoute: typeof BriefingRoute
  ContractsRoute: typeof ContractsRoute
  CrossrefRoute: typeof CrossrefRoute
  DonationsRoute: typeof DonationsRoute
  ExpensesRoute: typeof ExpensesRoute
  FoiRoute: typeof FoiRoute
  LobbyingRoute: typeof LobbyingRoute
  MeetingsRoute: typeof MeetingsRoute
  NewsRoute: typeof NewsRoute
  NhsRoute: typeof NhsRoute
  ParliamentRoute: typeof ParliamentRoute
  PartiesRoute: typeof PartiesRoute
  PetitionsRoute: typeof PetitionsRoute
  SanctionsRoute: typeof SanctionsRoute
  SewageRoute: typeof SewageRoute
  StopSearchRoute: typeof StopSearchRoute
  VotesRoute: typeof VotesRoute
  ApiAcobaRoute: typeof ApiAcobaRoute
  ApiBillsRoute: typeof ApiBillsRoute
  ApiBriefingRoute: typeof ApiBriefingRoute
  ApiContractsRoute: typeof ApiContractsRoute
  ApiDonationsRoute: typeof ApiDonationsRoute
  ApiExpensesRoute: typeof ApiExpensesRoute
  ApiFoiRoute: typeof ApiFoiRoute
  ApiKpisRoute: typeof ApiKpisRoute
  ApiLobbyingRoute: typeof ApiLobbyingRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiNhsRoute: typeof ApiNhsRoute
  ApiPartiesRoute: typeof ApiPartiesRoute
  ApiPetitionsRoute: typeof ApiPetitionsRoute
  ApiSanctionsRoute: typeof ApiSanctionsRoute
  ApiSewageRoute: typeof ApiSewageRoute
  ApiStopSearchRoute: typeof ApiStopSearchRoute
  ApiVotesRoute: typeof ApiVotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/votes': {
      id: '/votes'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-search': {
      id: '/stop-search'
      path: '/stop-search'
      fullPath: '/stop-search'
      preLoaderRoute: typeof StopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewage': {
      id: '/sewage'
      path: '/sewage'
      fullPath: '/sewage'
      preLoaderRoute: typeof SewageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions': {
      id: '/petitions'
      path: '/petitions'
      fullPath: '/petitions'
      preLoaderRoute: typeof PetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament': {
      id: '/parliament'
      path: '/parliament'
      fullPath: '/parliament'
      preLoaderRoute: typeof ParliamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhs': {
      id: '/nhs'
      path: '/nhs'
      fullPath: '/nhs'
      preLoaderRoute: typeof NhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbying': {
      id: '/lobbying'
      path: '/lobbying'
      fullPath: '/lobbying'
      preLoaderRoute: typeof LobbyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foi': {
      id: '/foi'
      path: '/foi'
      fullPath: '/foi'
      preLoaderRoute: typeof FoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossref': {
      id: '/crossref'
      path: '/crossref'
      fullPath: '/crossref'
      preLoaderRoute: typeof CrossrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoba': {
      id: '/acoba'
      path: '/acoba'
      fullPath: '/acoba'
      preLoaderRoute: typeof AcobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes': {
      id: '/api/votes'
      path: '/api/votes'
      fullPath: '/api/votes'
      preLoaderRoute: typeof ApiVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stop-search': {
      id: '/api/stop-search'
      path: '/api/stop-search'
      fullPath: '/api/stop-search'
      preLoaderRoute: typeof ApiStopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sewage': {
      id: '/api/sewage'
      path: '/api/sewage'
      fullPath: '/api/sewage'
      preLoaderRoute: typeof ApiSewageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sanctions': {
      id: '/api/sanctions'
      path: '/api/sanctions'
      fullPath: '/api/sanctions'
      preLoaderRoute: typeof ApiSanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/petitions': {
      id: '/api/petitions'
      path: '/api/petitions'
      fullPath: '/api/petitions'
      preLoaderRoute: typeof ApiPetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parties': {
      id: '/api/parties'
      path: '/api/parties'
      fullPath: '/api/parties'
      preLoaderRoute: typeof ApiPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nhs': {
      id: '/api/nhs'
      path: '/api/nhs'
      fullPath: '/api/nhs'
      preLoaderRoute: typeof ApiNhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lobbying': {
      id: '/api/lobbying'
      path: '/api/lobbying'
      fullPath: '/api/lobbying'
      preLoaderRoute: typeof ApiLobbyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kpis': {
      id: '/api/kpis'
      path: '/api/kpis'
      fullPath: '/api/kpis'
      preLoaderRoute: typeof ApiKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foi': {
      id: '/api/foi'
      path: '/api/foi'
      fullPath: '/api/foi'
      preLoaderRoute: typeof ApiFoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations': {
      id: '/api/donations'
      path: '/api/donations'
      fullPath: '/api/donations'
      preLoaderRoute: typeof ApiDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contracts': {
      id: '/api/contracts'
      path: '/api/contracts'
      fullPath: '/api/contracts'
      preLoaderRoute: typeof ApiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefing': {
      id: '/api/briefing'
      path: '/api/briefing'
      fullPath: '/api/briefing'
      preLoaderRoute: typeof ApiBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills': {
      id: '/api/bills'
      path: '/api/bills'
      fullPath: '/api/bills'
      preLoaderRoute: typeof ApiBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/acoba': {
      id: '/api/acoba'
      path: '/api/acoba'
      fullPath: '/api/acoba'
      preLoaderRoute: typeof ApiAcobaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcobaRoute: AcobaRoute,
  BriefingRoute: BriefingRoute,
  ContractsRoute: ContractsRoute,
  CrossrefRoute: CrossrefRoute,
  DonationsRoute: DonationsRoute,
  ExpensesRoute: ExpensesRoute,
  FoiRoute: FoiRoute,
  LobbyingRoute: LobbyingRoute,
  MeetingsRoute: MeetingsRoute,
  NewsRoute: NewsRoute,
  NhsRoute: NhsRoute,
  ParliamentRoute: ParliamentRoute,
  PartiesRoute: PartiesRoute,
  PetitionsRoute: PetitionsRoute,
  SanctionsRoute: SanctionsRoute,
  SewageRoute: SewageRoute,
  StopSearchRoute: StopSearchRoute,
  VotesRoute: VotesRoute,
  ApiAcobaRoute: ApiAcobaRoute,
  ApiBillsRoute: ApiBillsRoute,
  ApiBriefingRoute: ApiBriefingRoute,
  ApiContractsRoute: ApiContractsRoute,
  ApiDonationsRoute: ApiDonationsRoute,
  ApiExpensesRoute: ApiExpensesRoute,
  ApiFoiRoute: ApiFoiRoute,
  ApiKpisRoute: ApiKpisRoute,
  ApiLobbyingRoute: ApiLobbyingRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiNhsRoute: ApiNhsRoute,
  ApiPartiesRoute: ApiPartiesRoute,
  ApiPetitionsRoute: ApiPetitionsRoute,
  ApiSanctionsRoute: ApiSanctionsRoute,
  ApiSewageRoute: ApiSewageRoute,
  ApiStopSearchRoute: ApiStopSearchRoute,
  ApiVotesRoute: ApiVotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
