/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ForFirmsRouteImport } from './routes/for-firms'
import { Route as AgentRaterRouteImport } from './routes/agent-rater'
import { Route as PlanningRadarRouteImport } from './routes/planning-radar'
import { Route as LeaseAuditRouteImport } from './routes/lease-audit'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFirmsRoute = ForFirmsRouteImport.update({
  id: '/for-firms',
  path: '/for-firms',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRaterRoute = AgentRaterRouteImport.update({
  id: '/agent-rater',
  path: '/agent-rater',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRadarRoute = PlanningRadarRouteImport.update({
  id: '/planning-radar',
  path: '/planning-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseAuditRoute = LeaseAuditRouteImport.update({
  id: '/lease-audit',
  path: '/lease-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lease-audit': typeof LeaseAuditRoute
  '/planning-radar': typeof PlanningRadarRoute
  '/agent-rater': typeof AgentRaterRoute
  '/for-firms': typeof ForFirmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lease-audit': typeof LeaseAuditRoute
  '/planning-radar': typeof PlanningRadarRoute
  '/agent-rater': typeof AgentRaterRoute
  '/for-firms': typeof ForFirmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lease-audit': typeof LeaseAuditRoute
  '/planning-radar': typeof PlanningRadarRoute
  '/agent-rater': typeof AgentRaterRoute
  '/for-firms': typeof ForFirmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lease-audit' | '/planning-radar' | '/agent-rater' | '/for-firms' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lease-audit' | '/planning-radar' | '/agent-rater' | '/for-firms' | '/sitemap.xml'
  id: '__root__' | '/' | '/lease-audit' | '/planning-radar' | '/agent-rater' | '/for-firms' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaseAuditRoute: typeof LeaseAuditRoute
  PlanningRadarRoute: typeof PlanningRadarRoute
  AgentRaterRoute: typeof AgentRaterRoute
  ForFirmsRoute: typeof ForFirmsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-firms': {
      id: '/for-firms'
      path: '/for-firms'
      fullPath: '/for-firms'
      preLoaderRoute: typeof ForFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-rater': {
      id: '/agent-rater'
      path: '/agent-rater'
      fullPath: '/agent-rater'
      preLoaderRoute: typeof AgentRaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning-radar': {
      id: '/planning-radar'
      path: '/planning-radar'
      fullPath: '/planning-radar'
      preLoaderRoute: typeof PlanningRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease-audit': {
      id: '/lease-audit'
      path: '/lease-audit'
      fullPath: '/lease-audit'
      preLoaderRoute: typeof LeaseAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaseAuditRoute: LeaseAuditRoute,
  PlanningRadarRoute: PlanningRadarRoute,
  AgentRaterRoute: AgentRaterRoute,
  ForFirmsRoute: ForFirmsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
