// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpjrtodtzlgdqzwghejt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwanJ0b2R0emxnZHF6d2doZWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTIxNjEsImV4cCI6MjA2OTU2ODE2MX0.OWWZNNNkH1ojp3GBBzHQ5_ATRhRvqmTVYYuarO8al8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});