import { Link, Outlet, useLocation } from "@tanstack/react-router";
import { cn } from "@/lib/utils";

const NAV = [
  { to: "/", label: "Dashboard" },
  { to: "/petitions", label: "Petitions" },
  { to: "/contracts", label: "Contracts" },
  { to: "/parliament", label: "Parliament" },
  { to: "/expenses", label: "Expenses" },
  { to: "/briefing", label: "Briefing" },
  { to: "/votes", label: "Votes" },
  { to: "/lobbying", label: "Lobbying" },
  { to: "/acoba", label: "Revolving Door" },
] as const;

export function SiteShell() {
  const loc = useLocation();
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-surface/60 backdrop-blur sticky top-0 z-40">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-4 flex items-center justify-between gap-6">
          <Link to="/" className="flex items-baseline gap-2">
            <span className="font-display text-2xl font-black tracking-tight">
              transparen<span className="text-amber">C</span>
            </span>
            <span className="hidden sm:inline label-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
              UK gov accountability
            </span>
          </Link>
          <nav className="hidden md:flex items-center gap-1">
            {NAV.map((n) => {
              const active =
                n.to === "/" ? loc.pathname === "/" : loc.pathname.startsWith(n.to);
              return (
                <Link
                  key={n.to}
                  to={n.to}
                  className={cn(
                    "px-3 py-1.5 text-sm rounded-md label-mono uppercase tracking-wider transition-colors",
                    active
                      ? "bg-amber/10 text-amber"
                      : "text-muted-foreground hover:text-foreground hover:bg-surface-2",
                  )}
                >
                  {n.label}
                </Link>
              );
            })}
          </nav>
        </div>
        <div className="md:hidden border-t border-border overflow-x-auto">
          <div className="flex gap-1 px-4 py-2 min-w-max">
            {NAV.map((n) => {
              const active =
                n.to === "/" ? loc.pathname === "/" : loc.pathname.startsWith(n.to);
              return (
                <Link
                  key={n.to}
                  to={n.to}
                  className={cn(
                    "px-3 py-1 text-xs rounded label-mono uppercase tracking-wider",
                    active ? "bg-amber/10 text-amber" : "text-muted-foreground",
                  )}
                >
                  {n.label}
                </Link>
              );
            })}
          </div>
        </div>
      </header>
      <main className="mx-auto max-w-7xl px-4 sm:px-6 py-8">
        <Outlet />
      </main>
      <footer className="border-t border-border mt-16">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-8 text-xs text-muted-foreground space-y-2">
          <p className="label-mono uppercase tracking-wider">
            transparenC — built on open public data
          </p>
          <p>
            Data sources: UK Parliament Petitions API, Parliament Bills API,
            Contracts Finder, IPSA. Most content licensed under the{" "}
            <a
              href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
              className="underline hover:text-amber"
              target="_blank"
              rel="noreferrer"
            >
              Open Government Licence v3.0
            </a>
            . AI briefings generated by Lovable AI; verify against primary sources.
          </p>
        </div>
      </footer>
    </div>
  );
}