import {
  Banknote,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Car,
  CheckCircle,
  ClipboardList,
  Compass,
  CreditCard,
  DollarSign,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  HandHelping,
  Heart,
  Home,
  HelpCircle,
  Info,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Menu,
  PiggyBank,
  PlugZap,
  ReceiptText,
  Scale,
  Scroll,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Umbrella,
  User,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-react";

// Map lucide icon names (as strings from content data) to components.
// Add entries here as content authors use new icon names.
const iconMap: Record<string, React.ElementType> = {
  Banknote,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Car,
  CheckCircle,
  ClipboardList,
  Compass,
  CreditCard,
  DollarSign,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  HandHelping,
  Heart,
  Home,
  HelpCircle,
  Info,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Menu,
  PiggyBank,
  PlugZap,
  ReceiptText,
  Scale,
  Scroll,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Umbrella,
  User,
  Users,
  Wallet,
  X,
  Zap,
};

interface IconProps {
  name: string;
  className?: string;
  "aria-hidden"?: boolean;
}

export function Icon({ name, className, "aria-hidden": ariaHidden = true }: IconProps) {
  const Component = iconMap[name] ?? HelpCircle;
  return <Component className={className} aria-hidden={ariaHidden} />;
}
